### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by rockroman** [rockroman/CI_PP5_Blade#32]
As an **authenticated user/customer,** I would like to have the option to **contact team or the site owner** for **any inquiries or assistance related to products or orders**. 

## Acceptance Criteria
<ul>
    <li>Authenticated users/customers should have a visible option or link to contact the team or site owner.</li>
     <li>The contact form or communication channel should include fields for the user to provide their name, email address, and a message explaining their inquiry or request for assistance.</li>
     <li>The user should receive a confirmation message or notification after submitting their inquiry or request.</li>
</ul>

# Tasks
- [x] Create a link in navigation for the contact form
- [x] Create contact form with "send message" functionality
- [x] Add notifications to the user
