### ISSUE TITLE
Site owner product deletion

### ISSUE THREAD

**Issue by rockroman** [rockroman/CI_PP5_Blade#37]
As a **site owner,** I want to be able to **delete existing products from the webshop** that are no longer **available or relevant.**

## Acceptance Criteria
<ul>
    <li>The site owner should have a delete button or a link clearly displayed</li>
     <li>The deletion process should provide a confirmation prompt or mechanism to ensure the site owner's intention to delete the selected product.</li>
    
</ul>

# Tasks
- [x] Create a delete button
- [x] delete functionality should be implemented
- [x] Create a confirmation prompt to delete product
