### ISSUE TITLE
User Story :Store product details

### ISSUE THREAD

**Issue by rockroman** [rockroman/CI_PP5_Blade#7]
As a **unauthenticated user/customer** I would Like **to see details of a product on a website such as(description, and price)** so **I can save time searching for the thing I need**

## Acceptance Criteria
<ul>
    <li> When on the website finding the product I like to purchase details of the product are clearly displayed</li>
     <li> Easy and intuitive link or button to find product details</li>
  
</ul>

# Tasks
- [x] Create a template for product details
- [x] Add links or buttons from all products page to product details page 
- [x] Display product details
