### ISSUE TITLE
User Story :Filtering functionality

### ISSUE THREAD

**Issue by rockroman** [rockroman/CI_PP5_Blade#8]
As a **user/customer** I would like **functionality to refine my search of products on a website by Price, rating, and alphabet** so **that I can save time and narrow down the selection to only what I need**

## Acceptance Criteria
<ul>
    <li>When on the website products page, the filtering option is clearly displayed </li>
     <li>When navigating the filtering  menu clear list of filtering options that are relevant to the product is displayed</li>
     <li>Clicking on each option produces desired filtering result</li>
</ul>

# Tasks
- [x] Create a filtering section 
- [x] Display relevant filtering options 
- [x] Make links display proper results
